version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - echo "Updating system packages..."
      - yum update -y
      - echo "Installing dependencies..."
      - yum install -y unzip tar gzip

      - echo "Checking and Updating AWS CLI..."
      - if aws --version; then 
          echo "AWS CLI already installed. Updating..."; 
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip";
          unzip -q awscliv2.zip;
          sudo ./aws/install --update;
          rm -rf awscliv2.zip aws;
        else 
          echo "AWS CLI not found. Installing...";
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip";
          unzip -q awscliv2.zip;
          sudo ./aws/install;
          rm -rf awscliv2.zip aws;
        fi

      - echo "Checking and Updating AWS SAM CLI..."
      - if sam --version; then 
          echo "SAM CLI already installed. Updating..."; 
          curl -Lo aws-sam-cli-linux-x86_64.zip https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-x86_64.zip;
          unzip -q aws-sam-cli-linux-x86_64.zip -d sam-installation;
          sudo ./sam-installation/install;
          rm -rf aws-sam-cli-linux-x86_64.zip sam-installation;
        else 
          echo "SAM CLI not found. Installing...";
          curl -Lo aws-sam-cli-linux-x86_64.zip https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-x86_64.zip;
          unzip -q aws-sam-cli-linux-x86_64.zip -d sam-installation;
          sudo ./sam-installation/install;
          rm -rf aws-sam-cli-linux-x86_64.zip sam-installation;
        fi

      - export PATH=$PATH:/usr/local/bin

  pre_build:
    commands:
      - echo "Verifying AWS CLI and SAM CLI installation..."
      - aws --version
      - sam --version
      # - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
      # - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
      # - aws configure set region $AWS_REGION
      - echo "AWS CLI and SAM CLI are configured successfully."

  build:
    commands:
      - echo "Deploying first phase (without Lambda permissions)..."
      - sam build
      - sam deploy --stack-name $STACK_NAME --parameter-overrides AuthId=NONE --no-fail-on-empty-changeset

      - echo "Waiting for API Gateway creation..."
      - sleep 90  # Increase sleep time to allow API Gateway to be fully available

      - echo "Fetching API Gateway ID..."
      - |
        API_ID=$(aws apigateway get-rest-apis --query "items[?name=='wellinkauthdevapitest'].id" --output text)
        echo "API Gateway ID: $API_ID"
        echo "API_ID=$API_ID" >> /tmp/env_variables.sh  # Save API ID for later use

      - echo "Fetching Authorizer ID..."
      - |
        AUTH_ID=$(aws apigateway get-authorizers --rest-api-id $API_ID --query "items[?name=='WellinksLambdaAuthorizer'].id" --output text)
        echo "Authorizer ID: $AUTH_ID"
        echo "AUTH_ID=$AUTH_ID" >> /tmp/env_variables.sh  # Save Auth ID for later use

      - echo "Deploying Lambda permission with dynamic Authorizer ID..."
      - source /tmp/env_variables.sh  # Load API_ID and AUTH_ID
      - sam deploy --stack-name $STACK_NAME --parameter-overrides AuthId=$AUTH_ID


artifacts:
  files:
    - '**/*'
