version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - echo "Installing AWS CLI and SAM CLI..."
      - apt-get update -y
      - apt-get install -y unzip
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip awscliv2.zip
      - sudo ./aws/install
      - curl -Lo aws-sam-cli-linux-x86_64.zip https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-x86_64.zip
      - unzip aws-sam-cli-linux-x86_64.zip -d sam-installation
      - sudo ./sam-installation/install
      - rm -rf awscliv2.zip aws sam-installation aws-sam-cli-linux-x86_64.zip
      - export PATH=$PATH:/usr/local/bin

  pre_build:
    commands:
      - echo "Configuring AWS CLI..."
      - aws --version
      - sam --version
      - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
      - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
      - aws configure set region $AWS_REGION
      - echo "AWS CLI and SAM CLI configured."

  build:
    commands:
      - echo "Running SAM sync..."
      - sam sync --stack-name wellinksauthdevstack --watch

artifacts:
  files:
    - '**/*'
