AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  AuthId:
    Type: String
    Description: "The API Gateway Authorizer ID"
    Default: "NONE"

Conditions:
  HasAuthId: !Not [!Equals [!Ref AuthId, "NONE"]]

Resources:
  LambdaStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: lambda/wellinks-auth-exp-dev/template.yaml

  ApiGatewayStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./apigateway/second-api-coming-soon/apigateway-template.yaml
      Parameters:
        AuthLambdaArn: !GetAtt LambdaStack.Outputs.WellinksAuthLambdaFunctionArn
        AuthId: !Ref AuthId  # Passing dynamic AuthId
