version = 0.1

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "lambda-authorizer-dev-test"
s3_bucket = "wellink-sam-auth-dev-test"
capabilities = "CAPABILITY_IAM"
region = "us-east-1"
confirm_changeset = false
