AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  WellinksAuthLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: wellinksauthdevfunctiontest
      Runtime: nodejs22.x
      Handler: index.handler
      CodeUri: ./lambdoooo
      MemorySize: 128
      Timeout: 5
      Policies:
        - AWSLambdaBasicExecutionRole

Outputs:
  WellinksAuthLambdaFunctionArn:
    Description: "ARN of the Lambda function"
    Value: !GetAtt WellinksAuthLambdaFunction.Arn
